version: '3'

services:
  indexer:
    build:
      context: ./src/workers/indexer
      dockerfile: Dockerfile
    container_name: indexer
    working_dir: /indexer
    volumes:
      - ./src/workers/indexer:/indexer
    depends_on:
    - redis
    network_mode: host
    restart: unless-stopped
  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    container_name: api
    working_dir: /api
    environment:
      PORT: 8001
    volumes:
      - ./src/api:/api
    depends_on:
    - redis
    network_mode: host
    restart: unless-stopped
  redis:
    image: redis
    network_mode: host
    restart: unless-stopped
